version: "3.3"

services:
  client:
    image: client:latest
    build: 
      context: .
      dockerfile: ./cmd/Dockerfile
      args:
        - APPTYPE=client
    environment:
      - CONTROL_WEBSOCKET_URI=ws://control:8081
      - CLIENT_ID=client
    depends_on:
      - websocket

  websocket:
    image: websocket:latest
    build: 
      context: .
      dockerfile: ./cmd/Dockerfile
      args:
        - APPTYPE=websocket
    ports:
      - "8080:8080"
    environment:
      - HTTP_PORT=8080
      - BACKEND_GRPC_SERVER=backend:9378

  control:
    image: control:latest
    build: 
      context: .
      dockerfile: ./cmd/Dockerfile
      args:
        - APPTYPE=control
    ports:
      - "8081:8081"
    environment:
      - HTTP_PORT=8081
      - BACKEND_GRPC_SERVER=backend:9378

  backend:
    image: backend:latest
    build: 
      context: .
      dockerfile: ./cmd/Dockerfile
      args:
        - APPTYPE=backend
    ports:
      - "9378:9378"
    environment:
      - BACKEND_SERVER_URI=0.0.0.0:9378
      - REDIS_URI=redis:6379

  proxy:
    image: proxy:latest
    build: 
      context: .
      dockerfile: ./cmd/Dockerfile
      args:
        - APPTYPE=proxy
    ports:
      - "9090:9090"
    environment:
      - PROXY_HTTP_PORT=9090
      - BACKEND_GRPC_SERVER=backend:9378

  debug:
    image: mendhak/http-https-echo:17 
    ports:
      - "7070:80"

  hello:
    image: tutum/hello-world
    ports:
      - "3030:80"

  redis:
    image: "redis:latest"
    command: redis-server 
    ports:
      - "6379:6379"
    environment: 
      - REDIS_REPLICATION_MODE=master
