// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: messages/v1/messages.proto

package messagespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientID string `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
	// Types that are assignable to MessageType:
	//	*ControlMessage_DiscoveryRequest
	//	*ControlMessage_DiscoveryResponse
	//	*ControlMessage_PipesRegistered
	//	*ControlMessage_Disconnect
	MessageType isControlMessage_MessageType `protobuf_oneof:"MessageType"`
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_v1_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_v1_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_messages_v1_messages_proto_rawDescGZIP(), []int{0}
}

func (x *ControlMessage) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

func (m *ControlMessage) GetMessageType() isControlMessage_MessageType {
	if m != nil {
		return m.MessageType
	}
	return nil
}

func (x *ControlMessage) GetDiscoveryRequest() *DiscoveryRequest {
	if x, ok := x.GetMessageType().(*ControlMessage_DiscoveryRequest); ok {
		return x.DiscoveryRequest
	}
	return nil
}

func (x *ControlMessage) GetDiscoveryResponse() *DiscoveryResponse {
	if x, ok := x.GetMessageType().(*ControlMessage_DiscoveryResponse); ok {
		return x.DiscoveryResponse
	}
	return nil
}

func (x *ControlMessage) GetPipesRegistered() *PipesRegistered {
	if x, ok := x.GetMessageType().(*ControlMessage_PipesRegistered); ok {
		return x.PipesRegistered
	}
	return nil
}

func (x *ControlMessage) GetDisconnect() *ForceDisconnect {
	if x, ok := x.GetMessageType().(*ControlMessage_Disconnect); ok {
		return x.Disconnect
	}
	return nil
}

type isControlMessage_MessageType interface {
	isControlMessage_MessageType()
}

type ControlMessage_DiscoveryRequest struct {
	DiscoveryRequest *DiscoveryRequest `protobuf:"bytes,2,opt,name=discoveryRequest,proto3,oneof"`
}

type ControlMessage_DiscoveryResponse struct {
	DiscoveryResponse *DiscoveryResponse `protobuf:"bytes,3,opt,name=discoveryResponse,proto3,oneof"`
}

type ControlMessage_PipesRegistered struct {
	PipesRegistered *PipesRegistered `protobuf:"bytes,4,opt,name=pipesRegistered,proto3,oneof"`
}

type ControlMessage_Disconnect struct {
	Disconnect *ForceDisconnect `protobuf:"bytes,5,opt,name=disconnect,proto3,oneof"`
}

func (*ControlMessage_DiscoveryRequest) isControlMessage_MessageType() {}

func (*ControlMessage_DiscoveryResponse) isControlMessage_MessageType() {}

func (*ControlMessage_PipesRegistered) isControlMessage_MessageType() {}

func (*ControlMessage_Disconnect) isControlMessage_MessageType() {}

type Client struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientID string `protobuf:"bytes,1,opt,name=ClientID,proto3" json:"ClientID,omitempty"`
}

func (x *Client) Reset() {
	*x = Client{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_v1_messages_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Client) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Client) ProtoMessage() {}

func (x *Client) ProtoReflect() protoreflect.Message {
	mi := &file_messages_v1_messages_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Client.ProtoReflect.Descriptor instead.
func (*Client) Descriptor() ([]byte, []int) {
	return file_messages_v1_messages_proto_rawDescGZIP(), []int{1}
}

func (x *Client) GetClientID() string {
	if x != nil {
		return x.ClientID
	}
	return ""
}

type DiscoveryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Client *Client `protobuf:"bytes,1,opt,name=Client,proto3" json:"Client,omitempty"`
}

func (x *DiscoveryRequest) Reset() {
	*x = DiscoveryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_v1_messages_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscoveryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryRequest) ProtoMessage() {}

func (x *DiscoveryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_messages_v1_messages_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryRequest.ProtoReflect.Descriptor instead.
func (*DiscoveryRequest) Descriptor() ([]byte, []int) {
	return file_messages_v1_messages_proto_rawDescGZIP(), []int{2}
}

func (x *DiscoveryRequest) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

type DiscoveryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataPlaneURI string `protobuf:"bytes,1,opt,name=DataPlaneURI,proto3" json:"DataPlaneURI,omitempty"`
}

func (x *DiscoveryResponse) Reset() {
	*x = DiscoveryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_v1_messages_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiscoveryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiscoveryResponse) ProtoMessage() {}

func (x *DiscoveryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_messages_v1_messages_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiscoveryResponse.ProtoReflect.Descriptor instead.
func (*DiscoveryResponse) Descriptor() ([]byte, []int) {
	return file_messages_v1_messages_proto_rawDescGZIP(), []int{3}
}

func (x *DiscoveryResponse) GetDataPlaneURI() string {
	if x != nil {
		return x.DataPlaneURI
	}
	return ""
}

type PipesRegistered struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Successful bool `protobuf:"varint,1,opt,name=Successful,proto3" json:"Successful,omitempty"`
}

func (x *PipesRegistered) Reset() {
	*x = PipesRegistered{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_v1_messages_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PipesRegistered) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipesRegistered) ProtoMessage() {}

func (x *PipesRegistered) ProtoReflect() protoreflect.Message {
	mi := &file_messages_v1_messages_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipesRegistered.ProtoReflect.Descriptor instead.
func (*PipesRegistered) Descriptor() ([]byte, []int) {
	return file_messages_v1_messages_proto_rawDescGZIP(), []int{4}
}

func (x *PipesRegistered) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

type ForceDisconnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Successful bool `protobuf:"varint,1,opt,name=Successful,proto3" json:"Successful,omitempty"`
}

func (x *ForceDisconnect) Reset() {
	*x = ForceDisconnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_messages_v1_messages_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ForceDisconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForceDisconnect) ProtoMessage() {}

func (x *ForceDisconnect) ProtoReflect() protoreflect.Message {
	mi := &file_messages_v1_messages_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForceDisconnect.ProtoReflect.Descriptor instead.
func (*ForceDisconnect) Descriptor() ([]byte, []int) {
	return file_messages_v1_messages_proto_rawDescGZIP(), []int{5}
}

func (x *ForceDisconnect) GetSuccessful() bool {
	if x != nil {
		return x.Successful
	}
	return false
}

var File_messages_v1_messages_proto protoreflect.FileDescriptor

var file_messages_v1_messages_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x22, 0xd6, 0x02, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x48, 0x0a, 0x10, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x10, 0x64,
	0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x4b, 0x0a, 0x11, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00, 0x52, 0x11, 0x64, 0x69, 0x73, 0x63, 0x6f,
	0x76, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x45, 0x0a, 0x0f,
	0x70, 0x69, 0x70, 0x65, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x50, 0x69, 0x70, 0x65, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64,
	0x48, 0x00, 0x52, 0x0f, 0x70, 0x69, 0x70, 0x65, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x65, 0x64, 0x12, 0x3b, 0x0a, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x73, 0x2e, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x42, 0x0d, 0x0a, 0x0b, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x24, 0x0a, 0x06, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x3c, 0x0a, 0x10, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x28, 0x0a, 0x06, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x73, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x22, 0x37, 0x0a, 0x11, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x44, 0x61, 0x74, 0x61,
	0x50, 0x6c, 0x61, 0x6e, 0x65, 0x55, 0x52, 0x49, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x44, 0x61, 0x74, 0x61, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x55, 0x52, 0x49, 0x22, 0x31, 0x0a, 0x0f,
	0x50, 0x69, 0x70, 0x65, 0x73, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x65, 0x64, 0x12,
	0x1e, 0x0a, 0x0a, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x08, 0x52, 0x0a, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c, 0x22,
	0x31, 0x0a, 0x0f, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66, 0x75, 0x6c,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x66,
	0x75, 0x6c, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x3b, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_messages_v1_messages_proto_rawDescOnce sync.Once
	file_messages_v1_messages_proto_rawDescData = file_messages_v1_messages_proto_rawDesc
)

func file_messages_v1_messages_proto_rawDescGZIP() []byte {
	file_messages_v1_messages_proto_rawDescOnce.Do(func() {
		file_messages_v1_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_messages_v1_messages_proto_rawDescData)
	})
	return file_messages_v1_messages_proto_rawDescData
}

var file_messages_v1_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_messages_v1_messages_proto_goTypes = []interface{}{
	(*ControlMessage)(nil),    // 0: messages.ControlMessage
	(*Client)(nil),            // 1: messages.Client
	(*DiscoveryRequest)(nil),  // 2: messages.DiscoveryRequest
	(*DiscoveryResponse)(nil), // 3: messages.DiscoveryResponse
	(*PipesRegistered)(nil),   // 4: messages.PipesRegistered
	(*ForceDisconnect)(nil),   // 5: messages.ForceDisconnect
}
var file_messages_v1_messages_proto_depIdxs = []int32{
	2, // 0: messages.ControlMessage.discoveryRequest:type_name -> messages.DiscoveryRequest
	3, // 1: messages.ControlMessage.discoveryResponse:type_name -> messages.DiscoveryResponse
	4, // 2: messages.ControlMessage.pipesRegistered:type_name -> messages.PipesRegistered
	5, // 3: messages.ControlMessage.disconnect:type_name -> messages.ForceDisconnect
	1, // 4: messages.DiscoveryRequest.Client:type_name -> messages.Client
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_messages_v1_messages_proto_init() }
func file_messages_v1_messages_proto_init() {
	if File_messages_v1_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_messages_v1_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ControlMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_v1_messages_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Client); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_v1_messages_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscoveryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_v1_messages_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiscoveryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_v1_messages_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PipesRegistered); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_messages_v1_messages_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ForceDisconnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_messages_v1_messages_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ControlMessage_DiscoveryRequest)(nil),
		(*ControlMessage_DiscoveryResponse)(nil),
		(*ControlMessage_PipesRegistered)(nil),
		(*ControlMessage_Disconnect)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_messages_v1_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_v1_messages_proto_goTypes,
		DependencyIndexes: file_messages_v1_messages_proto_depIdxs,
		MessageInfos:      file_messages_v1_messages_proto_msgTypes,
	}.Build()
	File_messages_v1_messages_proto = out.File
	file_messages_v1_messages_proto_rawDesc = nil
	file_messages_v1_messages_proto_goTypes = nil
	file_messages_v1_messages_proto_depIdxs = nil
}
