// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: websocket/v1/websocket.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDataPlaneUriRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Client *Client `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
}

func (x *GetDataPlaneUriRequest) Reset() {
	*x = GetDataPlaneUriRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_websocket_v1_websocket_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataPlaneUriRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataPlaneUriRequest) ProtoMessage() {}

func (x *GetDataPlaneUriRequest) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_v1_websocket_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataPlaneUriRequest.ProtoReflect.Descriptor instead.
func (*GetDataPlaneUriRequest) Descriptor() ([]byte, []int) {
	return file_websocket_v1_websocket_proto_rawDescGZIP(), []int{0}
}

func (x *GetDataPlaneUriRequest) GetClient() *Client {
	if x != nil {
		return x.Client
	}
	return nil
}

type GetDataPlaneUriResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataPlaneUri string `protobuf:"bytes,1,opt,name=data_plane_uri,json=dataPlaneUri,proto3" json:"data_plane_uri,omitempty"`
}

func (x *GetDataPlaneUriResponse) Reset() {
	*x = GetDataPlaneUriResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_websocket_v1_websocket_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDataPlaneUriResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDataPlaneUriResponse) ProtoMessage() {}

func (x *GetDataPlaneUriResponse) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_v1_websocket_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDataPlaneUriResponse.ProtoReflect.Descriptor instead.
func (*GetDataPlaneUriResponse) Descriptor() ([]byte, []int) {
	return file_websocket_v1_websocket_proto_rawDescGZIP(), []int{1}
}

func (x *GetDataPlaneUriResponse) GetDataPlaneUri() string {
	if x != nil {
		return x.DataPlaneUri
	}
	return ""
}

type TextNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *TextNotification) Reset() {
	*x = TextNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_websocket_v1_websocket_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextNotification) ProtoMessage() {}

func (x *TextNotification) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_v1_websocket_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextNotification.ProtoReflect.Descriptor instead.
func (*TextNotification) Descriptor() ([]byte, []int) {
	return file_websocket_v1_websocket_proto_rawDescGZIP(), []int{2}
}

func (x *TextNotification) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ClientRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to RequestType:
	//	*ClientRequest_GetDataPlaneUriRequest
	//	*ClientRequest_RegisterConnectionRequest
	RequestType isClientRequest_RequestType `protobuf_oneof:"RequestType"`
}

func (x *ClientRequest) Reset() {
	*x = ClientRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_websocket_v1_websocket_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequest) ProtoMessage() {}

func (x *ClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_websocket_v1_websocket_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequest.ProtoReflect.Descriptor instead.
func (*ClientRequest) Descriptor() ([]byte, []int) {
	return file_websocket_v1_websocket_proto_rawDescGZIP(), []int{3}
}

func (m *ClientRequest) GetRequestType() isClientRequest_RequestType {
	if m != nil {
		return m.RequestType
	}
	return nil
}

func (x *ClientRequest) GetGetDataPlaneUriRequest() *GetDataPlaneUriRequest {
	if x, ok := x.GetRequestType().(*ClientRequest_GetDataPlaneUriRequest); ok {
		return x.GetDataPlaneUriRequest
	}
	return nil
}

func (x *ClientRequest) GetRegisterConnectionRequest() *RegisterConnectionRequest {
	if x, ok := x.GetRequestType().(*ClientRequest_RegisterConnectionRequest); ok {
		return x.RegisterConnectionRequest
	}
	return nil
}

type isClientRequest_RequestType interface {
	isClientRequest_RequestType()
}

type ClientRequest_GetDataPlaneUriRequest struct {
	GetDataPlaneUriRequest *GetDataPlaneUriRequest `protobuf:"bytes,1,opt,name=get_data_plane_uri_request,json=getDataPlaneUriRequest,proto3,oneof"`
}

type ClientRequest_RegisterConnectionRequest struct {
	RegisterConnectionRequest *RegisterConnectionRequest `protobuf:"bytes,2,opt,name=register_connection_request,json=registerConnectionRequest,proto3,oneof"`
}

func (*ClientRequest_GetDataPlaneUriRequest) isClientRequest_RequestType() {}

func (*ClientRequest_RegisterConnectionRequest) isClientRequest_RequestType() {}

var File_websocket_v1_websocket_proto protoreflect.FileDescriptor

var file_websocket_v1_websocket_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x77, 0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x77,
	0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x77, 0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x1a, 0x1b, 0x77, 0x65, 0x62, 0x73, 0x6f,
	0x63, 0x6b, 0x65, 0x74, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f,
	0x76, 0x31, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x43, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x50, 0x6c, 0x61, 0x6e, 0x65,
	0x55, 0x72, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x06, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x77, 0x65, 0x62,
	0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x06, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x3f, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x50, 0x6c, 0x61, 0x6e, 0x65, 0x55, 0x72, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x24, 0x0a, 0x0e, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x6c, 0x61, 0x6e, 0x65, 0x5f, 0x75,
	0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x64, 0x61, 0x74, 0x61, 0x50, 0x6c,
	0x61, 0x6e, 0x65, 0x55, 0x72, 0x69, 0x22, 0x26, 0x0a, 0x10, 0x54, 0x65, 0x78, 0x74, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x22, 0xe5,
	0x01, 0x0a, 0x0d, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x5f, 0x0a, 0x1a, 0x67, 0x65, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x70, 0x6c, 0x61,
	0x6e, 0x65, 0x5f, 0x75, 0x72, 0x69, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x77, 0x65, 0x62, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74,
	0x2e, 0x47, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x55, 0x72, 0x69,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x16, 0x67, 0x65, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x50, 0x6c, 0x61, 0x6e, 0x65, 0x55, 0x72, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x64, 0x0a, 0x1b, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x5f, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x19, 0x72, 0x65,
	0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x42, 0x0d, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x3b, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_websocket_v1_websocket_proto_rawDescOnce sync.Once
	file_websocket_v1_websocket_proto_rawDescData = file_websocket_v1_websocket_proto_rawDesc
)

func file_websocket_v1_websocket_proto_rawDescGZIP() []byte {
	file_websocket_v1_websocket_proto_rawDescOnce.Do(func() {
		file_websocket_v1_websocket_proto_rawDescData = protoimpl.X.CompressGZIP(file_websocket_v1_websocket_proto_rawDescData)
	})
	return file_websocket_v1_websocket_proto_rawDescData
}

var file_websocket_v1_websocket_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_websocket_v1_websocket_proto_goTypes = []interface{}{
	(*GetDataPlaneUriRequest)(nil),    // 0: websocket.GetDataPlaneUriRequest
	(*GetDataPlaneUriResponse)(nil),   // 1: websocket.GetDataPlaneUriResponse
	(*TextNotification)(nil),          // 2: websocket.TextNotification
	(*ClientRequest)(nil),             // 3: websocket.ClientRequest
	(*Client)(nil),                    // 4: websocket.Client
	(*RegisterConnectionRequest)(nil), // 5: backend.RegisterConnectionRequest
}
var file_websocket_v1_websocket_proto_depIdxs = []int32{
	4, // 0: websocket.GetDataPlaneUriRequest.client:type_name -> websocket.Client
	0, // 1: websocket.ClientRequest.get_data_plane_uri_request:type_name -> websocket.GetDataPlaneUriRequest
	5, // 2: websocket.ClientRequest.register_connection_request:type_name -> backend.RegisterConnectionRequest
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_websocket_v1_websocket_proto_init() }
func file_websocket_v1_websocket_proto_init() {
	if File_websocket_v1_websocket_proto != nil {
		return
	}
	file_websocket_v1_messages_proto_init()
	file_backend_v1_backend_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_websocket_v1_websocket_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataPlaneUriRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_websocket_v1_websocket_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDataPlaneUriResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_websocket_v1_websocket_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_websocket_v1_websocket_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_websocket_v1_websocket_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*ClientRequest_GetDataPlaneUriRequest)(nil),
		(*ClientRequest_RegisterConnectionRequest)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_websocket_v1_websocket_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_websocket_v1_websocket_proto_goTypes,
		DependencyIndexes: file_websocket_v1_websocket_proto_depIdxs,
		MessageInfos:      file_websocket_v1_websocket_proto_msgTypes,
	}.Build()
	File_websocket_v1_websocket_proto = out.File
	file_websocket_v1_websocket_proto_rawDesc = nil
	file_websocket_v1_websocket_proto_goTypes = nil
	file_websocket_v1_websocket_proto_depIdxs = nil
}
