FROM golang:alpine AS builder

# Create /duplexity and ~/.ssh
RUN mkdir -p /duplexity ~/.ssh

# Install necessary build tools
RUN apk update && apk upgrade && apk add --no-cache bash git openssh

RUN ls 
# Copy repo into build container
COPY . /duplexity

# Move to the client
WORKDIR /duplexity/cmd/client
RUN ls
# Build binary in /duplexity called client
RUN ["go", "build", "-o", "/duplexity/client"]

FROM alpine

# Create /duplexity and move there
WORKDIR /duplexity
# Copy binary from builder
COPY --from=builder /duplexity/client .
RUN ls 
# Run binary
CMD ./client